apiVersion: batch/v1
kind: Job
metadata:
  name: data-modeling-manual
  namespace: data-platform
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: data-modeling
          image: ghcr.io/prabhusathy2008/martech-data-platform/data-modeling:v1
          imagePullPolicy: Always
          env:
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
