apiVersion: batch/v1
kind: Job
metadata:
  name: dl-ingestion-manual
  namespace: data-platform
spec:
  backoffLimit: 1
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: dl-ingestion
          image: ghcr.io/prabhusathy2008/martech-data-platform/dl-ingestion:v1
          imagePullPolicy: Always
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: MINIO_ROOT_PASSWORD