name: github_engagement_analytics
version: 1.0.0
config-version: 2

profile: github_engagement_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  github_engagement_analytics:
    staging:
      +materialized: view
      +tags: ['staging']
    intermediate:
      +materialized: view
      +tags: ['intermediate']
    marts:
      +materialized: table
      +tags: ['marts']